## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Talnakh,RU,69.4865,88.3972,1.20,96,99,6.58,overcast clouds
1,1,Deder,ET,9.3167,41.4500,55.56,10,2,5.53,clear sky
2,2,Upernavik,GL,72.7868,-56.1549,-3.08,100,93,9.84,overcast clouds
3,3,Faya,SA,18.3851,42.4509,57.31,87,32,6.67,scattered clouds
4,4,Vaini,TO,-21.2000,-175.2000,75.36,100,100,13.80,light rain
5,5,Chapais,CA,49.7834,-74.8492,-4.22,92,97,3.49,overcast clouds
6,6,Rikitea,PF,-23.1203,-134.9692,78.44,71,12,7.72,light rain
7,7,Saint-Augustin,CA,51.2260,-58.6502,-0.81,84,100,7.16,overcast clouds
8,8,Severo-Kurilsk,RU,50.6789,156.1250,28.98,94,100,6.17,light snow
9,9,Dikson,RU,73.5069,80.5464,-4.45,95,100,6.35,overcast clouds

In [3]:
city_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              691 non-null    int64
 1   City                 691 non-null    object
 2   Country              684 non-null    object
 3   Lat                  691 non-null    float64
 4   Lng                  691 non-null    float64
 5   Max Temp             691 non-null    float64
 6   Humidity             691 non-null    int64
 7   Cloudiness           691 non-null    int64
 8   Wind Speed           691 non-null    float64
 9   Current Description  691 non-null    object
dtypes: float64(4), int64(3), object(3)
memory usage: 54.1+ KB

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [7]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
4,4,Vaini,TO,-21.2000,-175.2000,75.36,100,100,13.80,light rain
6,6,Rikitea,PF,-23.1203,-134.9692,78.44,71,12,7.72,light rain
12,12,Presidencia Roque Saenz Pena,AR,-26.7852,-60.4388,70.66,96,96,7.40,light rain
17,17,Bambous Virieux,MU,-20.3428,57.7575,80.22,94,75,18.41,light rain
19,19,Carnarvon,AU,-24.8667,113.6333,75.27,73,75,8.05,broken clouds
20,20,Bujaru,BR,-1.5150,-48.0447,77.02,98,100,2.53,light rain
27,27,Puerto Ayora,EC,-0.7393,-90.3518,82.36,89,82,4.00,broken clouds
31,31,Aitape,PG,-3.1374,142.3475,79.38,83,75,5.23,broken clouds
43,43,Sinnamary,GF,5.3833,-52.9500,76.26,88,100,8.37,overcast clouds
49,49,Avarua,CK,-21.2078,-159.7750,84.25,74,20,16.11,few clouds

In [8]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                2
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [9]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna(subset=["Country"])

In [10]:
clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Vaini,TO,75.36,light rain,-21.2000,-175.2000,
6,Rikitea,PF,78.44,light rain,-23.1203,-134.9692,
12,Presidencia Roque Saenz Pena,AR,70.66,light rain,-26.7852,-60.4388,
17,Bambous Virieux,MU,80.22,light rain,-20.3428,57.7575,
19,Carnarvon,AU,75.27,broken clouds,-24.8667,113.6333,
20,Bujaru,BR,77.02,light rain,-1.5150,-48.0447,
27,Puerto Ayora,EC,82.36,broken clouds,-0.7393,-90.3518,
31,Aitape,PG,79.38,broken clouds,-3.1374,142.3475,
43,Sinnamary,GF,76.26,overcast clouds,5.3833,-52.9500,
49,Avarua,CK,84.25,few clouds,-21.2078,-159.7750,

In [12]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [13]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Vaini,TO,75.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
6,Rikitea,PF,78.44,light rain,-23.1203,-134.9692,People ThankYou
12,Presidencia Roque Saenz Pena,AR,70.66,light rain,-26.7852,-60.4388,Hotel Gualok
17,Bambous Virieux,MU,80.22,light rain,-20.3428,57.7575,Casa Tia Villa
19,Carnarvon,AU,75.27,broken clouds,-24.8667,113.6333,Hospitality Carnarvon
20,Bujaru,BR,77.02,light rain,-1.5150,-48.0447,Hotel & Restaurante Beira Rio
27,Puerto Ayora,EC,82.36,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
31,Aitape,PG,79.38,broken clouds,-3.1374,142.3475,
43,Sinnamary,GF,76.26,overcast clouds,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
49,Avarua,CK,84.25,few clouds,-21.2078,-159.7750,Paradise Inn

In [14]:
hotel_df.count()

City                   236
Country                236
Max Temp               236
Current Description    236
Lat                    236
Lng                    236
Hotel Name             236
dtype: int64

In [15]:
# 7. Drop the rows where there is no Hotel Name.
import numpy as np
hotel_df["Hotel Name"].replace("", np.NaN, inplace=True)
clean_hotel_df = hotel_df.dropna(how = "any")
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Vaini,TO,75.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
6,Rikitea,PF,78.44,light rain,-23.1203,-134.9692,People ThankYou
12,Presidencia Roque Saenz Pena,AR,70.66,light rain,-26.7852,-60.4388,Hotel Gualok
17,Bambous Virieux,MU,80.22,light rain,-20.3428,57.7575,Casa Tia Villa
19,Carnarvon,AU,75.27,broken clouds,-24.8667,113.6333,Hospitality Carnarvon
20,Bujaru,BR,77.02,light rain,-1.5150,-48.0447,Hotel & Restaurante Beira Rio
27,Puerto Ayora,EC,82.36,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
43,Sinnamary,GF,76.26,overcast clouds,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
49,Avarua,CK,84.25,few clouds,-21.2078,-159.7750,Paradise Inn
52,Isangel,VU,77.11,light rain,-19.5500,169.2667,Tanna Lodge

In [16]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [58]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

AttributeError: module 'collections' has no attribute 'Iterable'